### PR TITLE
Fix and disable warnings

### PR DESCRIPTION
**Pull request by kspaceKelvin**
Fix and disable various warnings

### CODE REVIEW

**Comment by hansenms** [comment]
@kspaceKelvin what is the status of this. Could we dust it off and see if we can merge?

**Comment by dchansen** [comment]
Fixing warnings is good, disabling warnings - not so much. It messes up the code and gives a false sense of security.

**Comment by hansenms** [comment]
@kspaceKelvin could you check if #171 captures all of what you wanted to get done. If so we can merge that and close this one.

**Comment by hansenms** [comment]
@kspaceKelvin closing this now since #171 has been merged. Please reopen if there are still issues.

**Pull request closed without merging**
