### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by pvelasco**
Fixed link to API.
I'm sorry it shows as changed all of the file: it must be the formatting...

### CODE REVIEW

**Comment by naegelejd** [comment]
Not your fault Pablo but we can't merge this because it appears as if you changed every line in the file but it's just a problem with line ending characters. Are you on a Windows machine?
The fastest option would be to edit `README.md` in your fork in your browser directly, then re-submit the PR.

**Comment by pvelasco** [comment]
Hi Joe,

I edited it on my browser (Safari, on a Mac).  You can just edit it yourself: the link to the API is:
https://ismrmrd.github.io/api/

-Pablo

**Comment by naegelejd** [comment]
Hmm, this is confusing. I already updated this link in `README.md` in 1bc4ed824c36ff878feef117a0e0077f7eccb769.

**Comment by pvelasco** [comment]
No, the one I meant is in /ismrmrd/doc/source/index.rst

**Comment by naegelejd** [comment]
Oh right, sorry about that. Thanks!

**Pull request closed without merging**
