### PR TITLE
use stdbool.h on VS2013 or later

### PR DESCRIPTION
**Pull request by KrisThielemans**
Fixes Issue #82

### CODE REVIEW

**Comment by hansenms** [comment]
@xueh2 can you check this on Windows.

**Comment by xueh2** [comment]
The PR is compiled successfully in windows VS2015. There are a few warnings:

ismrmrd.cpp
1>D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(103): warning C4297: **'ISMRMRD::Acquisition::~Acquisition': function assumed not to throw an exception but does**
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(103): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(404): warning C4297: **'ISMRMRD::Image<uint16_t>::~Image': function assumed not to throw an exception but does**
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(404): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(402): note: while compiling class template member function 'ISMRMRD::Image<uint16_t>::~Image(void)'
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1181): note: see reference to class template instantiation 'ISMRMRD::Image<uint16_t>' being compiled
1>D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(404): warning C4297: 'ISMRMRD::Image<int16_t>::~Image': function assumed not to throw an exception but does
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(404): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(402): note: while compiling class template member function 'ISMRMRD::Image<int16_t>::~Image(void)'
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1182): note: see reference to class template instantiation 'ISMRMRD::Image<int16_t>' being compiled
1>D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(404): warning C4297: 'ISMRMRD::Image<uint32_t>::~Image': function assumed not to throw an exception but does
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(404): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(402): note: while compiling class template member function 'ISMRMRD::Image<uint32_t>::~Image(void)'
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1183): note: see reference to class template instantiation 'ISMRMRD::Image<uint32_t>' being compiled
1>D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(404): warning C4297: 'ISMRMRD::Image<int32_t>::~Image': function assumed not to throw an exception but does
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(404): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(402): note: while compiling class template member function 'ISMRMRD::Image<int32_t>::~Image(void)'
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1184): note: see reference to class template instantiation 'ISMRMRD::Image<int32_t>' being compiled
1>D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(404): warning C4297: 'ISMRMRD::Image<float>::~Image': function assumed not to throw an exception but does
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(404): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(402): note: while compiling class template member function 'ISMRMRD::Image<float>::~Image(void)'
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1185): note: see reference to class template instantiation 'ISMRMRD::Image<float>' being compiled
1>D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(404): warning C4297: 'ISMRMRD::Image<double>::~Image': function assumed not to throw an exception but does
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(404): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(402): note: while compiling class template member function 'ISMRMRD::Image<double>::~Image(void)'
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1186): note: see reference to class template instantiation 'ISMRMRD::Image<double>' being compiled
1>D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(404): warning C4297: 'ISMRMRD::Image<complex_float_t>::~Image': function assumed not to throw an exception but does
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(404): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(402): note: while compiling class template member function 'ISMRMRD::Image<complex_float_t>::~Image(void)'
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1187): note: see reference to class template instantiation 'ISMRMRD::Image<complex_float_t>' being compiled
1>D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(404): warning C4297: 'ISMRMRD::Image<complex_double_t>::~Image': function assumed not to throw an exception but does
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(404): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(402): note: while compiling class template member function 'ISMRMRD::Image<complex_double_t>::~Image(void)'
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1188): note: see reference to class template instantiation 'ISMRMRD::Image<complex_double_t>' being compiled
1>D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1043): warning C4297: 'ISMRMRD::NDArray<uint16_t>::~NDArray': function assumed not to throw an exception but does
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1043): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1041): note: while compiling class template member function 'ISMRMRD::NDArray<uint16_t>::~NDArray(void)'
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1191): note: see reference to class template instantiation 'ISMRMRD::NDArray<uint16_t>' being compiled
1>D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1043): warning C4297: 'ISMRMRD::NDArray<int16_t>::~NDArray': function assumed not to throw an exception but does
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1043): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1041): note: while compiling class template member function 'ISMRMRD::NDArray<int16_t>::~NDArray(void)'
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1192): note: see reference to class template instantiation 'ISMRMRD::NDArray<int16_t>' being compiled
1>D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1043): warning C4297: 'ISMRMRD::NDArray<uint32_t>::~NDArray': function assumed not to throw an exception but does
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1043): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1041): note: while compiling class template member function 'ISMRMRD::NDArray<uint32_t>::~NDArray(void)'
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1193): note: see reference to class template instantiation 'ISMRMRD::NDArray<uint32_t>' being compiled
1>D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1043): warning C4297: 'ISMRMRD::NDArray<int32_t>::~NDArray': function assumed not to throw an exception but does
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1043): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1041): note: while compiling class template member function 'ISMRMRD::NDArray<int32_t>::~NDArray(void)'
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1194): note: see reference to class template instantiation 'ISMRMRD::NDArray<int32_t>' being compiled
1>D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1043): warning C4297: 'ISMRMRD::NDArray<float>::~NDArray': function assumed not to throw an exception but does
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1043): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1041): note: while compiling class template member function 'ISMRMRD::NDArray<float>::~NDArray(void)'
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1195): note: see reference to class template instantiation 'ISMRMRD::NDArray<float>' being compiled
1>D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1043): warning C4297: 'ISMRMRD::NDArray<double>::~NDArray': function assumed not to throw an exception but does
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1043): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1041): note: while compiling class template member function 'ISMRMRD::NDArray<double>::~NDArray(void)'
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1196): note: see reference to class template instantiation 'ISMRMRD::NDArray<double>' being compiled
1>D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1043): warning C4297: 'ISMRMRD::NDArray<complex_float_t>::~NDArray': function assumed not to throw an exception but does
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1043): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1041): note: while compiling class template member function 'ISMRMRD::NDArray<complex_float_t>::~NDArray(void)'
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1197): note: see reference to class template instantiation 'ISMRMRD::NDArray<complex_float_t>' being compiled
1>D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1043): warning C4297: 'ISMRMRD::NDArray<complex_double_t>::~NDArray': function assumed not to throw an exception but does
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1043): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1041): note: while compiling class template member function 'ISMRMRD::NDArray<complex_double_t>::~NDArray(void)'
1>  D:\gtuser\mrprogs\ismrmrd\libsrc\ismrmrd.cpp(1198): note: see reference to class template instantiation 'ISMRMRD::NDArray<complex_double_t>' being compiled

**Comment by hansenms** [comment]
@xueh2  These warnings are not related to the patch, right? They are there either way?

**Comment by xueh2** [comment]
Yes, these warnings are there before the patch. The patch is fine then.

**Pull request merged**
