### PR TITLE
making HDF5 optional

### PR DESCRIPTION
**Pull request by naegelejd**

### CODE REVIEW

**Comment by ghisvail** [comment]
I'll try it for Windows on my Philips VM (VS 2008). It won't happen before Wednesday.

**Comment by naegelejd** [comment]
Updated to address some issues @inati mentioned:

- CMake now issues a warning if HDF5 is not found
- `ismrmrd_info` now prints whether ISMRMRD is installed with dataset support

**Comment by inati** [comment]
Update minor version number?

**Comment by naegelejd** [comment]
If you're asking me I presume you mean "increment the patch number". Major is for breaking changes to fixed memory layout structs, minor is for changes to XML schema.

**Pull request merged**
