### PR TITLE
Add ability to read HDF5 files in read-only mode

### PR DESCRIPTION
**Pull request by isolovey-robarts**
Currently one must have write permissions to the ismrmrd (HDF5) file in order to read it in. This change adds a fallback read-only call to H5Fopen if the read-write mode call fails.

### CODE REVIEW

**Comment by inati** [comment]
We should probably have a state so that we can give a meaningful error when the user tries to perform a write operation.

**Comment by hansenms** [comment]
@inati, fair point, but isn't this PR better than what we have after all? @naegelejd, thoughts?

I propose we merge this and then we can add the state later??

**Comment by naegelejd** [comment]
Looks good

**Comment by inati** [comment]
Okay.   @naegelejd let's discuss the state and/or a way to indicate a warning.

**Pull request merged**
