### PR TITLE
add patientHeight_m into SubjectInformation

### PR DESCRIPTION
**Pull request by achataigner**

### CODE REVIEW

**Comment by achataigner** [comment]
Hi,

Is someone available to review this branch ?

**Comment by achataigner** [comment]
Hi, anyone to review this pr ?

**Comment by hansenms** [comment]
@achataigner  Should we dust this off and see if we can get it merged. If you update hashes, etc. And we would have to go to 1.6.0.  Then I can take a look.

**Comment by achataigner** [comment]
Hi Michael, thank you for your interest.
Branch rebased on last master, just let me know if other changes are required

**Comment by hansenms** [comment]
We need to bump the minor version.

**Comment by achataigner** [comment]
done

**Comment by hansenms** [comment]
Thanks. Can I get one of the matlab folks @kristofferknudsen, @ojosephs to take a look, since it touches the Matlab stuff and we have no tests I can lean on. I think otherwise, this looks good to me.

**Comment by hansenms** [comment]
@kspaceKelvin can you take this for a spin while we think through automated Matlab testing.

**Review by dchansen — APPROVED** [review]

**Pull request merged**
